# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About: /about

# Customize
customize:
    logo:
        width: 165
        height: 60
        url: images/logo-header.png
    theme_color: '#3b8dbd'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        #twitter: /
        facebook: https://www.facebook.com/profile.php?id=100001913447948
        #google-plus: /
        github: https://github.com/acupple
        weibo: http://weibo.com/1605653652/info
        renren: http://www.renren.com/222009767
        #rss: /

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: acupple # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: bdshare # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    scrollLoading: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key
    

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
